language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  - DEPS=latest
  - DEPS=lowest

branches:
  only:
    master

before_install:
  - travis_retry composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction --prefer-source ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi

script:
  - composer check-style
  - composer test-with-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
