language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

branches:
  only:
    master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=./clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f ./clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
