language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS=""
    - TMPDIR=/tmp
    - USE_XDEBUG=false
    - COMPOSER_DISCARD_CHANGES=1

branches:
  only:
    master

before_script:
  - if [[ "$USE_XDEBUG" == false ]]; then phpenv config-rm xdebug.ini || return 0; fi

install:
  - phpenv rehash
  - travis_retry composer update --no-interaction --prefer-source $COMPOSER_ARGS

stages:
  - test
  - test with coverage

script:
  - composer test

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.4
    - php: nightly
  include:
    - php: 7.1
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.1
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.3
    - php: 7.4
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.4
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs --prefer-lowest"
    - php: nightly
      env: COMPOSER_ARGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.3
      env: TMPDIR=/tmp USE_XDEBUG=true
      script:
        - composer test-with-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ./clover.xml
